### ISSUE TITLE
@usernames addressing not working when using a symbol right after the username

### ISSUE THREAD

**Issue by sneakySensei** [gitaalekhyapaul/chat-app-api#2]
"Hey @admin great project" -- Works
"Hey @admin, great project" -- Doesn't work
"Hey @admin. Great project" -- Doesn't work either

PS. The response still returns a success

**Comment by gitaalekhyapaul** [comment]
As per the API Documentation, I have mentioned that, only if the users are found then, the message will go to their inbox. I haven't implemented a user search there, which will be a feature update soon.
